image: docker:24.0.5

services:
  - docker:24.0.5-dind

stages:
  - test
  - build

test_app:
  stage: test
  script:
    - docker build -t lua-api-template:test .
    - docker compose run --rm test

build_image:
  stage: build
  script:
    - docker build -t my-registry/lua-api-template:latest .
  only:
    - main